## Load the Data

In [1]:
import pandas as pd
df=pd.read_csv("c:/users/deepa/downloads/heart_failure_clinical_records_dataset.csv")
df.head()

age  anaemia  creatinine_phosphokinase  diabetes  ejection_fraction  \
0  75.0        0                       582       0.0               20.0   
1  55.0        0                      7861       0.0               38.0   
2  65.0        0                       146       0.0               20.0   
3  50.0        1                       111       0.0               20.0   
4  65.0        1                       160       1.0               20.0   

   high_blood_pressure  platelets  serum_creatinine  serum_sodium  sex  \
0                    1  265000.00               1.9           130    1   
1                    0  263358.03               1.1           136    1   
2                    0  162000.00               1.3           129    1   
3                    0  210000.00               1.9           137    1   
4                    0  327000.00               2.7           116    0   

   smoking  time  DEATH_EVENT  
0        0     4            1  
1        0     6            1  
2        1     7            1  
3        0     7            1  
4        0     8            1

In [2]:
df['DEATH_EVENT'].value_counts()

0    203
1     96
Name: DEATH_EVENT, dtype: int64

## Clean and Analayze the data

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 299 entries, 0 to 298
Data columns (total 13 columns):
age                         299 non-null float64
anaemia                     299 non-null int64
creatinine_phosphokinase    299 non-null int64
diabetes                    298 non-null float64
ejection_fraction           297 non-null float64
high_blood_pressure         299 non-null int64
platelets                   299 non-null float64
serum_creatinine            299 non-null float64
serum_sodium                299 non-null int64
sex                         299 non-null int64
smoking                     299 non-null int64
time                        299 non-null int64
DEATH_EVENT                 299 non-null int64
dtypes: float64(5), int64(8)
memory usage: 30.5 KB


In [4]:
df.describe()

age     anaemia  creatinine_phosphokinase    diabetes  \
count  299.000000  299.000000                299.000000  298.000000   
mean    60.833893    0.431438                581.839465    0.419463   
std     11.894809    0.496107                970.287881    0.494301   
min     40.000000    0.000000                 23.000000    0.000000   
25%     51.000000    0.000000                116.500000    0.000000   
50%     60.000000    0.000000                250.000000    0.000000   
75%     70.000000    1.000000                582.000000    1.000000   
max     95.000000    1.000000               7861.000000    1.000000   

       ejection_fraction  high_blood_pressure      platelets  \
count         297.000000           299.000000     299.000000   
mean           38.013468             0.351171  263358.029264   
std            11.791538             0.478136   97804.236869   
min            14.000000             0.000000   25100.000000   
25%            30.000000             0.000000  212500.000000   
50%            38.000000             0.000000  262000.000000   
75%            45.000000             1.000000  303500.000000   
max            80.000000             1.000000  850000.000000   

       serum_creatinine  serum_sodium         sex    smoking        time  \
count         299.00000    299.000000  299.000000  299.00000  299.000000   
mean            1.39388    136.625418    0.648829    0.32107  130.260870   
std             1.03451      4.412477    0.478136    0.46767   77.614208   
min             0.50000    113.000000    0.000000    0.00000    4.000000   
25%             0.90000    134.000000    0.000000    0.00000   73.000000   
50%             1.10000    137.000000    1.000000    0.00000  115.000000   
75%             1.40000    140.000000    1.000000    1.00000  203.000000   
max             9.40000    148.000000    1.000000    1.00000  285.000000   

       DEATH_EVENT  
count    299.00000  
mean       0.32107  
std        0.46767  
min        0.00000  
25%        0.00000  
50%        0.00000  
75%        1.00000  
max        1.00000

#from above we came to know that there are sum null values present in the data, so we have to either remove the null values or add mean,mode or median.
#since the data we are using is very small we can impute the mean using Simple Imputer class of sklearn or using pandas attributes

In [5]:
df.isnull().sum()

age                         0
anaemia                     0
creatinine_phosphokinase    0
diabetes                    1
ejection_fraction           2
high_blood_pressure         0
platelets                   0
serum_creatinine            0
serum_sodium                0
sex                         0
smoking                     0
time                        0
DEATH_EVENT                 0
dtype: int64

In [6]:
df['diabetes'].isnull().sum()

1

In [7]:
df['ejection_fraction'].isnull().sum()

2

In [8]:
from sklearn.preprocessing import Imputer
imput=Imputer(strategy='median')
imputed_data=imput.fit_transform(df)
imputed_data

array([[7.500e+01, 0.000e+00, 5.820e+02, ..., 0.000e+00, 4.000e+00,
        1.000e+00],
       [5.500e+01, 0.000e+00, 7.861e+03, ..., 0.000e+00, 6.000e+00,
        1.000e+00],
       [6.500e+01, 0.000e+00, 1.460e+02, ..., 1.000e+00, 7.000e+00,
        1.000e+00],
       ...,
       [4.500e+01, 0.000e+00, 2.060e+03, ..., 0.000e+00, 2.780e+02,
        0.000e+00],
       [4.500e+01, 0.000e+00, 2.413e+03, ..., 1.000e+00, 2.800e+02,
        0.000e+00],
       [5.000e+01, 0.000e+00, 1.960e+02, ..., 1.000e+00, 2.850e+02,
        0.000e+00]])

In [9]:
print(imputed_data)

[[7.500e+01 0.000e+00 5.820e+02 ... 0.000e+00 4.000e+00 1.000e+00]
 [5.500e+01 0.000e+00 7.861e+03 ... 0.000e+00 6.000e+00 1.000e+00]
 [6.500e+01 0.000e+00 1.460e+02 ... 1.000e+00 7.000e+00 1.000e+00]
 ...
 [4.500e+01 0.000e+00 2.060e+03 ... 0.000e+00 2.780e+02 0.000e+00]
 [4.500e+01 0.000e+00 2.413e+03 ... 1.000e+00 2.800e+02 0.000e+00]
 [5.000e+01 0.000e+00 1.960e+02 ... 1.000e+00 2.850e+02 0.000e+00]]


In [10]:
df1=pd.DataFrame(imputed_data,columns=df.columns)
df1.head(25)

age  anaemia  creatinine_phosphokinase  diabetes  ejection_fraction  \
0   75.0      0.0                     582.0       0.0               20.0   
1   55.0      0.0                    7861.0       0.0               38.0   
2   65.0      0.0                     146.0       0.0               20.0   
3   50.0      1.0                     111.0       0.0               20.0   
4   65.0      1.0                     160.0       1.0               20.0   
5   90.0      1.0                      47.0       0.0               40.0   
6   75.0      1.0                     246.0       0.0               15.0   
7   60.0      1.0                     315.0       1.0               60.0   
8   65.0      0.0                     157.0       0.0               65.0   
9   80.0      1.0                     123.0       0.0               38.0   
10  75.0      1.0                      81.0       0.0               38.0   
11  62.0      0.0                     231.0       0.0               25.0   
12  45.0      1.0                     981.0       0.0               30.0   
13  50.0      1.0                     168.0       0.0               38.0   
14  49.0      1.0                      80.0       0.0               30.0   
15  82.0      1.0                     379.0       0.0               50.0   
16  87.0      1.0                     149.0       0.0               38.0   
17  45.0      0.0                     582.0       0.0               14.0   
18  70.0      1.0                     125.0       0.0               25.0   
19  48.0      1.0                     582.0       1.0               55.0   
20  65.0      1.0                      52.0       0.0               25.0   
21  65.0      1.0                     128.0       1.0               30.0   
22  68.0      1.0                     220.0       0.0               35.0   
23  53.0      0.0                      63.0       1.0               60.0   
24  75.0      0.0                     582.0       1.0               30.0   

    high_blood_pressure  platelets  serum_creatinine  serum_sodium  sex  \
0                   1.0  265000.00              1.90         130.0  1.0   
1                   0.0  263358.03              1.10         136.0  1.0   
2                   0.0  162000.00              1.30         129.0  1.0   
3                   0.0  210000.00              1.90         137.0  1.0   
4                   0.0  327000.00              2.70         116.0  0.0   
5                   1.0  204000.00              2.10         132.0  1.0   
6                   0.0  127000.00              1.20         137.0  1.0   
7                   0.0  454000.00              1.10         131.0  1.0   
8                   0.0  263358.03              1.50         138.0  0.0   
9                   1.0  388000.00              9.40         133.0  1.0   
10                  1.0  368000.00              4.00         131.0  1.0   
11                  1.0  253000.00              0.90         140.0  1.0   
12                  0.0  136000.00              1.10         137.0  1.0   
13                  1.0  276000.00              1.10         137.0  1.0   
14                  1.0  427000.00              1.00         138.0  0.0   
15                  0.0   47000.00              1.30         136.0  1.0   
16                  0.0  262000.00              0.90         140.0  1.0   
17                  0.0  166000.00              0.80         127.0  1.0   
18                  1.0  237000.00              1.00         140.0  0.0   
19                  0.0   87000.00              1.90         121.0  0.0   
20                  1.0  276000.00              1.30         137.0  0.0   
21                  1.0  297000.00              1.60         136.0  0.0   
22                  1.0  289000.00              0.90         140.0  1.0   
23                  0.0  368000.00              0.80         135.0  1.0   
24                  1.0  263358.03              1.83         134.0  0.0   

    smoking  time  DEATH_EVENT  
0       0.0   4.0          1.0  
1       0.0

In [11]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 299 entries, 0 to 298
Data columns (total 13 columns):
age                         299 non-null float64
anaemia                     299 non-null float64
creatinine_phosphokinase    299 non-null float64
diabetes                    299 non-null float64
ejection_fraction           299 non-null float64
high_blood_pressure         299 non-null float64
platelets                   299 non-null float64
serum_creatinine            299 non-null float64
serum_sodium                299 non-null float64
sex                         299 non-null float64
smoking                     299 non-null float64
time                        299 non-null float64
DEATH_EVENT                 299 non-null float64
dtypes: float64(13)
memory usage: 30.5 KB


In [12]:
df1.isnull().sum()

age                         0
anaemia                     0
creatinine_phosphokinase    0
diabetes                    0
ejection_fraction           0
high_blood_pressure         0
platelets                   0
serum_creatinine            0
serum_sodium                0
sex                         0
smoking                     0
time                        0
DEATH_EVENT                 0
dtype: int64

In [13]:
df1['diabetes'].value_counts()

0.0    174
1.0    125
Name: diabetes, dtype: int64

In [14]:
df1['DEATH_EVENT'].value_counts()

0.0    203
1.0     96
Name: DEATH_EVENT, dtype: int64

In [15]:
df1['anaemia'].value_counts()

0.0    170
1.0    129
Name: anaemia, dtype: int64

In [16]:
df1['high_blood_pressure'].value_counts()

0.0    194
1.0    105
Name: high_blood_pressure, dtype: int64

Above attribute clearly shows that now there are no null values present in the data.

## Analysing the data using plots and finding the correlation of features with other features as well as the target value

In [ ]:
import matplotlib.pyplot as plt
df1.hist(bins=50,figsize=(10,15))
plt.show()

In [ ]:
import seaborn as sns
sns.countplot(x=df1['anaemia'])

In [ ]:
sns.scatterplot(x=df1['DEATH_EVENT'],y=df1['time'],data=df1)

it indiccates that more number of people with anaemia has less death rates

In [ ]:
sns.countplot(x='smoking',data=df1)

In [ ]:
plt.scatter(x=df1['DEATH_EVENT'],y=df1['smoking'])

In [ ]:
corr_matrix=df1.corr()
corr_matrix['DEATH_EVENT'].sort_values(ascending=False)

In [ ]:
from pandas.plotting import scatter_matrix
attributes=['DEATH_EVENT','serum_creatinine','age','high_blood_pressure','anaemia','time','ejection_fraction','serum_sodium']
scatter_matrix(df1[attributes],figsize=(20,20))

 Normal range of serum creatinine in blood test
In Adult Male: 0.6-1.2 mg/dl
In Adult Female: 0.5-1.1 mg/dl

In [ ]:
plt.scatter(x=df1['age'],y=df1['serum_creatinine'])

In [ ]:
import seaborn as sns
corr=df1.corr()
fig,ax=plt.subplots(figsize=(20,10))
sns.heatmap(corr,cmap="GnBu",annot=True)

In [ ]:
sns.countplot(x='age',data=df1)

## Splitting the data into train test using

In [ ]:
x=df1.iloc[:,0:12]
y=df1.loc[:,'DEATH_EVENT']

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [ ]:
x_train.shape

In [ ]:
x_test.shape

In [ ]:
y_test.shape

## Using StandardScaler to standarise the dataset


In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
sc.fit(x_train)

In [ ]:
xtrain_scaled_data=sc.transform(x_train)
xtest_scaled_data=sc.transform(x_test)
xtest_scaled_data.shape

# Using Principal Component Analysis for Feature Selection

In [ ]:
from sklearn.decomposition import PCA
pca=PCA(n_components=6)
Xtrain=pca.fit_transform(xtrain_scaled_data)
Xtest=pca.transform(xtest_scaled_data)

In [ ]:
Xtrain.shape

In [ ]:
y_train.shape

In [ ]:
Xtest.shape

In [ ]:
pca.explained_variance_ratio_

In [ ]:
import numpy as np
cumsum=np.cumsum(pca.explained_variance_ratio_)
cumsum

In [ ]:
As you can see there is no benefit of using PCA as after extracting we are getting that 

## CREATING THE MODEL

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
model=DecisionTreeClassifier()
#model=RandomForestClassifier()
#model=LogisticRegression()

In [ ]:
from sklearn.model_selection import cross_val_score
cv=cross_val_score(model,Xtrain,y_train,cv=5,scoring="accuracy")
cv

In [ ]:
mean=cv.mean()
mean

In [ ]:
model.fit(Xtrain,y_train)

In [ ]:
y_train.shape

In [ ]:
y_test.value_counts()

In [ ]:
y_train.value_counts()

In [ ]:
predict=model.predict(Xtest)
predict

In [ ]:
y_test

In [ ]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [ ]:
print('Accuracy Score :',accuracy_score(y_test,predict))
print('Confusion Matrix :',confusion_matrix(y_test,predict))